<?php

/**
 * BaseP1ngProject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $p1ng_customer_id
 * @property string $code
 * @property string $name
 * @property P1ngCustomer $P1ngCustomer
 * @property Doctrine_Collection $issues
 * 
 * @method integer             getP1ngCustomerId()   Returns the current record's "p1ng_customer_id" value
 * @method string              getCode()             Returns the current record's "code" value
 * @method string              getName()             Returns the current record's "name" value
 * @method P1ngCustomer        getP1ngCustomer()     Returns the current record's "P1ngCustomer" value
 * @method Doctrine_Collection getIssues()           Returns the current record's "issues" collection
 * @method P1ngProject         setP1ngCustomerId()   Sets the current record's "p1ng_customer_id" value
 * @method P1ngProject         setCode()             Sets the current record's "code" value
 * @method P1ngProject         setName()             Sets the current record's "name" value
 * @method P1ngProject         setP1ngCustomer()     Sets the current record's "P1ngCustomer" value
 * @method P1ngProject         setIssues()           Sets the current record's "issues" collection
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngProject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_project');
        $this->hasColumn('p1ng_customer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('code', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '20',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('P1ngCustomer', array(
             'local' => 'p1ng_customer_id',
             'foreign' => 'id'));

        $this->hasMany('P1ngIssue as issues', array(
             'local' => 'id',
             'foreign' => 'p1ng_project_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($signable0);
    }
}