<?php

/**
 * BaseP1ngProjectRolePermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $p1ng_project_role_id
 * @property integer $sf_guard_permission_id
 * @property P1ngProjectRole $P1ngProjectRole
 * @property sfGuardPermission $sfGuardPermission
 * 
 * @method integer                   getP1ngProjectRoleId()      Returns the current record's "p1ng_project_role_id" value
 * @method integer                   getSfGuardPermissionId()    Returns the current record's "sf_guard_permission_id" value
 * @method P1ngProjectRole           getP1ngProjectRole()        Returns the current record's "P1ngProjectRole" value
 * @method sfGuardPermission         getSfGuardPermission()      Returns the current record's "sfGuardPermission" value
 * @method P1ngProjectRolePermission setP1ngProjectRoleId()      Sets the current record's "p1ng_project_role_id" value
 * @method P1ngProjectRolePermission setSfGuardPermissionId()    Sets the current record's "sf_guard_permission_id" value
 * @method P1ngProjectRolePermission setP1ngProjectRole()        Sets the current record's "P1ngProjectRole" value
 * @method P1ngProjectRolePermission setSfGuardPermission()      Sets the current record's "sfGuardPermission" value
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngProjectRolePermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_project_role_permission');
        $this->hasColumn('p1ng_project_role_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('sf_guard_permission_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('P1ngProjectRole', array(
             'local' => 'p1ng_project_role_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardPermission', array(
             'local' => 'sf_guard_permission_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}