<?php

/**
 * BaseP1ngIssueCustomField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $p1ng_issue_custom_field_definition_id
 * @property string $field_name
 * @property string $label
 * @property string $field_values
 * @property string $default_value
 * @property boolean $required
 * @property string $related_to_model
 * @property string $related_to_field
 * @property array $field_options
 * @property array $field_attributes
 * @property P1ngIssueCustomFieldDefinition $definition
 * 
 * @method integer                        getP1ngIssueCustomFieldDefinitionId()      Returns the current record's "p1ng_issue_custom_field_definition_id" value
 * @method string                         getFieldName()                             Returns the current record's "field_name" value
 * @method string                         getLabel()                                 Returns the current record's "label" value
 * @method string                         getFieldValues()                           Returns the current record's "field_values" value
 * @method string                         getDefaultValue()                          Returns the current record's "default_value" value
 * @method boolean                        getRequired()                              Returns the current record's "required" value
 * @method string                         getRelatedToModel()                        Returns the current record's "related_to_model" value
 * @method string                         getRelatedToField()                        Returns the current record's "related_to_field" value
 * @method array                          getFieldOptions()                          Returns the current record's "field_options" value
 * @method array                          getFieldAttributes()                       Returns the current record's "field_attributes" value
 * @method P1ngIssueCustomFieldDefinition getDefinition()                            Returns the current record's "definition" value
 * @method P1ngIssueCustomField           setP1ngIssueCustomFieldDefinitionId()      Sets the current record's "p1ng_issue_custom_field_definition_id" value
 * @method P1ngIssueCustomField           setFieldName()                             Sets the current record's "field_name" value
 * @method P1ngIssueCustomField           setLabel()                                 Sets the current record's "label" value
 * @method P1ngIssueCustomField           setFieldValues()                           Sets the current record's "field_values" value
 * @method P1ngIssueCustomField           setDefaultValue()                          Sets the current record's "default_value" value
 * @method P1ngIssueCustomField           setRequired()                              Sets the current record's "required" value
 * @method P1ngIssueCustomField           setRelatedToModel()                        Sets the current record's "related_to_model" value
 * @method P1ngIssueCustomField           setRelatedToField()                        Sets the current record's "related_to_field" value
 * @method P1ngIssueCustomField           setFieldOptions()                          Sets the current record's "field_options" value
 * @method P1ngIssueCustomField           setFieldAttributes()                       Sets the current record's "field_attributes" value
 * @method P1ngIssueCustomField           setDefinition()                            Sets the current record's "definition" value
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngIssueCustomField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_issue_custom_field');
        $this->hasColumn('p1ng_issue_custom_field_definition_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('field_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('label', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('field_values', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('default_value', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('required', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('related_to_model', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('related_to_field', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('field_options', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('field_attributes', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('P1ngIssueCustomFieldDefinition as definition', array(
             'local' => 'p1ng_issue_custom_field_definition_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($signable0);
    }
}