<?php

/**
 * BaseP1ngRowLevelAccess
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property integer $sf_guard_permission_id
 * @property varchar $namespace
 * @property varchar $value
 * @property sfGuardUser $sfGuardUser
 * @property sfGuardPermission $sfGuardPermission
 * 
 * @method integer            getSfGuardUserId()          Returns the current record's "sf_guard_user_id" value
 * @method integer            getSfGuardPermissionId()    Returns the current record's "sf_guard_permission_id" value
 * @method varchar            getNamespace()              Returns the current record's "namespace" value
 * @method varchar            getValue()                  Returns the current record's "value" value
 * @method sfGuardUser        getSfGuardUser()            Returns the current record's "sfGuardUser" value
 * @method sfGuardPermission  getSfGuardPermission()      Returns the current record's "sfGuardPermission" value
 * @method P1ngRowLevelAccess setSfGuardUserId()          Sets the current record's "sf_guard_user_id" value
 * @method P1ngRowLevelAccess setSfGuardPermissionId()    Sets the current record's "sf_guard_permission_id" value
 * @method P1ngRowLevelAccess setNamespace()              Sets the current record's "namespace" value
 * @method P1ngRowLevelAccess setValue()                  Sets the current record's "value" value
 * @method P1ngRowLevelAccess setSfGuardUser()            Sets the current record's "sfGuardUser" value
 * @method P1ngRowLevelAccess setSfGuardPermission()      Sets the current record's "sfGuardPermission" value
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngRowLevelAccess extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_row_level_access');
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('sf_guard_permission_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('namespace', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('value', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardPermission', array(
             'local' => 'sf_guard_permission_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}