<?php

/**
 * BaseP1ngProjectGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_group_id
 * @property integer $p1ng_project_id
 * @property integer $sf_guard_permission_id
 * @property sfGuardGroup $sfGuardGroup
 * @property P1ngProject $P1ngProject
 * @property sfGuardPermission $sfGuardPermission
 * 
 * @method integer                    getSfGuardGroupId()         Returns the current record's "sf_guard_group_id" value
 * @method integer                    getP1ngProjectId()          Returns the current record's "p1ng_project_id" value
 * @method integer                    getSfGuardPermissionId()    Returns the current record's "sf_guard_permission_id" value
 * @method sfGuardGroup               getSfGuardGroup()           Returns the current record's "sfGuardGroup" value
 * @method P1ngProject                getP1ngProject()            Returns the current record's "P1ngProject" value
 * @method sfGuardPermission          getSfGuardPermission()      Returns the current record's "sfGuardPermission" value
 * @method P1ngProjectGroupPermission setSfGuardGroupId()         Sets the current record's "sf_guard_group_id" value
 * @method P1ngProjectGroupPermission setP1ngProjectId()          Sets the current record's "p1ng_project_id" value
 * @method P1ngProjectGroupPermission setSfGuardPermissionId()    Sets the current record's "sf_guard_permission_id" value
 * @method P1ngProjectGroupPermission setSfGuardGroup()           Sets the current record's "sfGuardGroup" value
 * @method P1ngProjectGroupPermission setP1ngProject()            Sets the current record's "P1ngProject" value
 * @method P1ngProjectGroupPermission setSfGuardPermission()      Sets the current record's "sfGuardPermission" value
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngProjectGroupPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_project_group_permission');
        $this->hasColumn('sf_guard_group_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('p1ng_project_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('sf_guard_permission_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup', array(
             'local' => 'sf_guard_group_id',
             'foreign' => 'id'));

        $this->hasOne('P1ngProject', array(
             'local' => 'p1ng_project_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardPermission', array(
             'local' => 'sf_guard_permission_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}