<?php

/**
 * BaseP1ngProjectRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $P1ngProjectRoleUser
 * @property Doctrine_Collection $P1ngProjectRolePermission
 * 
 * @method string              getName()                      Returns the current record's "name" value
 * @method clob                getDescription()               Returns the current record's "description" value
 * @method Doctrine_Collection getP1ngProjectRoleUser()       Returns the current record's "P1ngProjectRoleUser" collection
 * @method Doctrine_Collection getP1ngProjectRolePermission() Returns the current record's "P1ngProjectRolePermission" collection
 * @method P1ngProjectRole     setName()                      Sets the current record's "name" value
 * @method P1ngProjectRole     setDescription()               Sets the current record's "description" value
 * @method P1ngProjectRole     setP1ngProjectRoleUser()       Sets the current record's "P1ngProjectRoleUser" collection
 * @method P1ngProjectRole     setP1ngProjectRolePermission() Sets the current record's "P1ngProjectRolePermission" collection
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngProjectRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_project_role');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('P1ngProjectRoleUser', array(
             'local' => 'id',
             'foreign' => 'p1ng_project_role_id'));

        $this->hasMany('P1ngProjectRolePermission', array(
             'local' => 'id',
             'foreign' => 'p1ng_project_role_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}