<?php

/**
 * BaseP1ngIssueCustomFieldDefinition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $label
 * @property clob $description
 * @property string $field_type
 * @property enum $widget
 * @property enum $validator
 * @property array $field_options
 * @property array $field_attributes
 * @property P1ngIssueCustomField $custom_field
 * 
 * @method string                         getName()             Returns the current record's "name" value
 * @method string                         getLabel()            Returns the current record's "label" value
 * @method clob                           getDescription()      Returns the current record's "description" value
 * @method string                         getFieldType()        Returns the current record's "field_type" value
 * @method enum                           getWidget()           Returns the current record's "widget" value
 * @method enum                           getValidator()        Returns the current record's "validator" value
 * @method array                          getFieldOptions()     Returns the current record's "field_options" value
 * @method array                          getFieldAttributes()  Returns the current record's "field_attributes" value
 * @method P1ngIssueCustomField           getCustomField()      Returns the current record's "custom_field" value
 * @method P1ngIssueCustomFieldDefinition setName()             Sets the current record's "name" value
 * @method P1ngIssueCustomFieldDefinition setLabel()            Sets the current record's "label" value
 * @method P1ngIssueCustomFieldDefinition setDescription()      Sets the current record's "description" value
 * @method P1ngIssueCustomFieldDefinition setFieldType()        Sets the current record's "field_type" value
 * @method P1ngIssueCustomFieldDefinition setWidget()           Sets the current record's "widget" value
 * @method P1ngIssueCustomFieldDefinition setValidator()        Sets the current record's "validator" value
 * @method P1ngIssueCustomFieldDefinition setFieldOptions()     Sets the current record's "field_options" value
 * @method P1ngIssueCustomFieldDefinition setFieldAttributes()  Sets the current record's "field_attributes" value
 * @method P1ngIssueCustomFieldDefinition setCustomField()      Sets the current record's "custom_field" value
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngIssueCustomFieldDefinition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_issue_custom_field_definition');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('label', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('field_type', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('widget', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'input_text',
              1 => 'textarea',
              2 => 'number',
              3 => 'enum',
             ),
             'default' => 'input_text',
             'notnull' => true,
             ));
        $this->hasColumn('validator', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'string',
             ),
             'default' => 'string',
             ));
        $this->hasColumn('field_options', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('field_attributes', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('P1ngIssueCustomField as custom_field', array(
             'local' => 'id',
             'foreign' => 'p1ng_issue_custom_field_definition_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}