<?php

/**
 * BaseP1ngCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property Doctrine_Collection $projects
 * 
 * @method string              getCode()     Returns the current record's "code" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getProjects() Returns the current record's "projects" collection
 * @method P1ngCustomer        setCode()     Sets the current record's "code" value
 * @method P1ngCustomer        setName()     Sets the current record's "name" value
 * @method P1ngCustomer        setProjects() Sets the current record's "projects" collection
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngCustomer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_customer');
        $this->hasColumn('code', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '20',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('P1ngProject as projects', array(
             'local' => 'id',
             'foreign' => 'p1ng_customer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($signable0);
    }
}