<?php

/**
 * BaseP1ngIssueLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $p1ng_issue_id
 * @property clob $text
 * @property P1ngIssue $P1ngIssue
 * 
 * @method integer      getP1ngIssueId()   Returns the current record's "p1ng_issue_id" value
 * @method clob         getText()          Returns the current record's "text" value
 * @method P1ngIssue    getP1ngIssue()     Returns the current record's "P1ngIssue" value
 * @method P1ngIssueLog setP1ngIssueId()   Sets the current record's "p1ng_issue_id" value
 * @method P1ngIssueLog setText()          Sets the current record's "text" value
 * @method P1ngIssueLog setP1ngIssue()     Sets the current record's "P1ngIssue" value
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseP1ngIssueLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p1ng_issue_log');
        $this->hasColumn('p1ng_issue_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('P1ngIssue', array(
             'local' => 'p1ng_issue_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($signable0);
    }
}