<?php

/**
 * P1ngWorkflow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class P1ngWorkflow extends BaseP1ngWorkflow
{
}
