<?php

/**
 * P1ngIssue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class P1ngIssue extends BaseP1ngIssue
{
	public function __toString()
	{
		return $this->getP1ngProject()->getP1ngCustomer()->getCode().':'.$this->getP1ngProject()->getCode().'-'.$this->getId();
	}
}
