<?php

/**
 * P1ngIssueCustomRow
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class P1ngIssueCustomRow extends BaseP1ngIssueCustomRow
{
  public function setTableDefinition()
  {
    parent::setTableDefinition();

    // during a build there are no tables yet
    try
    {
      // retrieve all currently active fields and register them to this table as columns
      $fields = Doctrine::getTable('P1ngIssueCustomField')->findAll();
      foreach ($fields as $field)
      {
        $this->hasColumn($field->getFieldName(), $field->getDefinition()->getFieldType(), null);
      }
    }
    catch (Exception $e)
    {
      // TODO: what to do here? We cannot log due to, during a build task, the context not existing yet
    }
  }

  /**
   * Returns all fields which are active for this row
   *
   * @return array
   */
  public function getCustomFields()
  {
    $date = (!$this->isNew()) ? $this->getP1ngIssue()->getCreatedAt() : time();

    return Doctrine::getTable('P1ngIssueCustomField')->findAllActiveForDate($date);
  }
}
