<?php

/**
 * P1ngIssueStatusTransition
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class P1ngIssueStatusTransition extends BaseP1ngIssueStatusTransition
{
  /**
   * Override to check if the destination status does not have any outgoing
   * transitions.
   *
   * When we do not check for this then it is possible for orphans to exist.
   *
   * @param Doctrine_Connection $conn
   * @return bool
   */
  public function delete(Doctrine_Connection $conn = null)
  {
    $destination = $this->getTo();

    // check if the destination has only one incoming (this one) and any outgoing
    if (($destination->getFrom()->count() == 1) && ($destination->getTo()->count() > 0))
    {
      throw new Exception('Unable to delete this transition, the destination status has outgoing dependencies and this is the only incoming');
    }

    return parent::delete($conn);
  }

}
