<?php

/**
 * P1ngIssue
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    p1ng
 * @subpackage model
 * @author     Mike van Riel <mike.vanriel@naenius.com>
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class P1ngIssue extends BaseP1ngIssue
{
  public function __toString()
  {
    return $this->getP1ngProject()->getP1ngCustomer()->getCode() . ':' . $this->getP1ngProject()->getCode() . '-' . $this->getId();
  }

  /**
   * Update the Lucene index during save.
   *
   * @param Doctrine_Connection $conn
   *
   * @return void
   */
  public function save(Doctrine_Connection $conn = null)
  {
    $conn = $conn ? $conn : $this->getTable()->getConnection();
    $conn->beginTransaction();
    try
    {
      $ret = parent::save($conn);
      $this->updateLuceneIndex();
      $conn->commit();
    }
    catch (Exception $e)
    {
      $conn->rollBack();
      throw $e;
    }

    return $ret;
  }

  /**
   * Override delete to clean the Lucene index.
   *
   * @param Doctrine_Connection $conn
   *
   * @return bool
   */
  public function delete(Doctrine_Connection $conn = null)
  {
    $index = P1ngIssueTable::getLuceneIndex();

    foreach ($index->find('pk:'.$this->getId()) as $hit)
    {
      $index->delete($hit->id);
    }

    return parent::delete($conn);
  }



  public function updateLuceneIndex()
  {
    $index = P1ngIssueTable::getLuceneIndex();

    // remove existing entries
    foreach ($index->find('pk:' . $this->getId()) as $hit)
    {
      $index->delete($hit->id);
    }

    $doc = new Zend_Search_Lucene_Document();

    // store job primary key to identify it in the search results
    $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));

    // index job fields
    $doc->addField(Zend_Search_Lucene_Field::text('key', (string)$this, 'utf-8'));
    $doc->addField(Zend_Search_Lucene_Field::text('subject', $this->getSubject(), 'utf-8'));
    $doc->addField(Zend_Search_Lucene_Field::unStored('status', (string)$this->getP1ngIssueStatus(), 'utf-8'));

    // custom fields are part of this issue and should be indexed with it
    foreach ($this->getCustom()->getCustomFields() as $field)
    {
      $doc->addField(Zend_Search_Lucene_Field::unStored($field->getFieldName(), (string)$this->getCustom()->get($field->getFieldName()), 'utf-8'));
    }

    // add job to the index
    $index->addDocument($doc);
    $index->commit();
  }
}
