homepage:
  url:   /
  param: { module: default, action: home }

admin:
  url:   /admin
  param: { module: default, action: admin }

p1ng_issue_custom_field:
  class: sfDoctrineRouteCollection
  options:
    model:                P1ngIssueCustomField
    module:               field
    prefix_path:          /field
    column:               id
    with_wildcard_routes: true

issue_search:
  url:   /issue/search/*
  param: { module: issue, action: search }

workflow_graph:
  url:   /workflow/:id/graph
  class: sfDoctrineRoute
  options: { model: P1ngWorkflow, type: object }
  param: { module: workflow, action: graph }

workflow:
  class: sfDoctrineRouteCollection
  options: { model: P1ngWorkflow }

transition:
  url:   /issue/:id/transition/:transition_id
  class: sfDoctrineRoute
  options: { model: P1ngIssue, type: object }
  param: { module: issue, action: transition }

issue:
  class: sfDoctrineRouteCollection
  options: { model: P1ngIssue }

log:
  class: sfDoctrineRouteCollection
  options: { model: P1ngIssueLog }

project:
  class: sfDoctrineRouteCollection
  options: { model: P1ngProject }
