homepage:
  class: sfDoctrineRoute
  url:   /
  param: { module: issue, action: index }
  options: { type: list, model: P1ngIssue }

p1ng_issue_custom_field:
  class: sfDoctrineRouteCollection
  options:
    model:                P1ngIssueCustomField
    module:               field
    prefix_path:          /field
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

transition:
  url:   /issue/:id/transition/:transition_id
  class: sfDoctrineRoute
  options: { model: P1ngIssue, type: object }
  param: { module: issue, action: transition }

issue:
  class: sfDoctrineRouteCollection
  options: { model: P1ngIssue }

log:
  class: sfDoctrineRouteCollection
  options: { model: P1ngIssueLog }

project:
  class: sfDoctrineRouteCollection
  options: { model: P1ngProject }
